- name: launching complete apache website
  hosts: 54.91.229.184 ansible_ssh_user=ubuntu
  become: true  
  tasks:
          - name: installing apache software
            apt:
                    name: apache2
                    state: present
          - name: copy index.html 
            copy:
                    src: index.html
                    dest: /var/www/html/
          - name: start the apche2 service
            service:
                    name: apache2
                    state: restarted

